sonar.projectKey=breco
sonar.projectName=Breco
sonar.projectVersion=2.0.0

# Sources
sonar.sources=frontend/breco/src,backend/breco/src
sonar.exclusions=**/node_modules/**,**/vendor/**,**/__tests__/**,**/dist/**

# Frontend
sonar.javascript.lcov.reportPaths=frontend/breco/coverage/lcov.info

# Backend
sonar.php.coverage.reportPaths=backend/breco/coverage/coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8