{
 "title": "Breco - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "NGINX connections waiting",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NGINX Active connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NGINX HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NGINX Accepted connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_accepted", "legendFormat": "__auto" }
   ]
  }
 ]
}