FROM php:8.4-cli-alpine
RUN apk add --no-cache sqlite sqlite-dev icu-dev icu-libs curl autoconf g++ make \
    && docker-php-ext-install pdo pdo_sqlite intl \
    && pecl install pcov \
    && docker-php-ext-enable pcov \
    && apk del sqlite-dev icu-dev autoconf g++ make