server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;    
    # Direct static files to frontend (xml, css, js, images)
    location /test-results/ {
        try_files $uri =404;
        add_header Content-Type application/xml;
    }
    # SPA fallback for Vue Router
    # All routes are handled by the frontend, allowing Vue Router to manage navigation.
    location / {
        try_files $uri $uri/ /index.html;
    }
}